name: Release Workflow

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  NODE_VERSION: 22.6.0
  PNPM_VERSION: 9.7.1
  KEEP: ".git .github dist publish"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Node setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          pnpm-run-install: true

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build Project
        run: pnpm run build

      - name: Push Built Packages to Version Branches
        run: |
          cd build
          for dir in */ ; do
            pkg_path="${dir}package.json"

            if [ -f "$pkg_path" ]; then
              name=$(jq -r .name "$pkg_path")
              version=$(jq -r .version "$pkg_path")
              branch="${name}@v${version}"
              branch=${branch//@/} # replace @ with nothing

              echo "📦 Creating branch $branch"

              git checkout --orphan "$branch"
              git rm -rf . > /dev/null 2>&1 || true
              cp -r "$dir"/* .
              git add .
              git commit -m "chore: release $name@$version"
              git push -f origin "$branch"
              git checkout -
            fi
          done
